dist: trusty

jobs: 
  include:
    - stage: 
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t oskarsportfolio:$TRAVIS_BUILD_NUMBER .
      - docker tag oskarsportfolio:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/oskarsportfolio
      - docker push $DOCKER_USERNAME/oskarsportfolio:latest
